"""Module for tracking processed project IDs.
This module was generated by AI, and provides functionality to track which project IDs
"""

import os
from pathlib import Path
from typing import Any, List, Set


class IDTracker:
    """Tracks which project IDs have been processed."""

    def __init__(self, tracking_file: str = "processed.txt"):
        """
        Initialize the ID tracker.

        Args:
            tracking_file: Path to the file where processed IDs are stored
        """
        self.tracking_file = Path(tracking_file)
        self.processed_ids: Set[int] = set()
        self._load_processed_ids()

    def _load_processed_ids(self) -> None:
        """Load processed IDs from the tracking file if it exists."""
        if self.tracking_file.exists():
            with open(self.tracking_file, "r") as f:
                for line in f:
                    line = line.strip()
                    if line:
                        try:
                            self.processed_ids.add(int(line))
                        except ValueError:
                            # Skip invalid lines
                            continue

    def is_processed(self, project_id: int) -> bool:
        """
        Check if a project ID has been processed.

        Args:
            project_id: The project ID to check

        Returns:
            True if the ID has been processed, False otherwise
        """
        return project_id in self.processed_ids

    def filter_unprocessed(self, projects: List[Any]) -> List[Any]:
        """
        Filter out already processed projects.

        Args:
            projects: List of project objects (must have 'id' attribute)

        Returns:
            List of unprocessed projects
        """
        unprocessed = [p for p in projects if p.id not in self.processed_ids]
        return unprocessed

    def mark_processed(self, project_id: int) -> None:
        """
        Mark a project ID as processed and save to file.

        Args:
            project_id: The project ID to mark as processed
        """
        if project_id not in self.processed_ids:
            self.processed_ids.add(project_id)
            self._append_to_file(project_id)

    def mark_batch_processed(self, project_ids: List[int]) -> None:
        """
        Mark multiple project IDs as processed and save to file.

        Args:
            project_ids: List of project IDs to mark as processed
        """
        new_ids = [pid for pid in project_ids if pid not in self.processed_ids]
        if new_ids:
            self.processed_ids.update(new_ids)
            with open(self.tracking_file, "a") as f:
                for pid in new_ids:
                    f.write(f"{pid}\n")

    def _append_to_file(self, project_id: int) -> None:
        """
        Append a single project ID to the tracking file.

        Args:
            project_id: The project ID to append
        """
        with open(self.tracking_file, "a") as f:
            f.write(f"{project_id}\n")

    def get_stats(self) -> dict:
        """
        Get statistics about processed projects.

        Returns:
            Dictionary with statistics
        """
        return {
            "total_processed": len(self.processed_ids),
            "tracking_file": str(self.tracking_file),
            "file_exists": self.tracking_file.exists(),
        }
